version: '3'
services:
  coopy:
    build:
      context: .
      dockerfile: Dockerfile_dev
    image: coopy-dev
    container_name: coopy-dev
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/src/coopy/
    tty: true
